### ISSUE TITLE
Version inconsistency on npm

### ISSUE THREAD

**Issue by N33MO** [Green-Software-Foundation/if-plugins#41]
package version inconsistent between npm and this repo
[Here](https://github.com/Green-Software-Foundation/if-models/releases) v0.1.5 is tagged as latest and v0.1.6-beta as Pre-release
In npm v0.1.6-beta is tagged as latest and this doesn't comply with existing yml files, users have to explicit download v0.1.5 to use the IF.
`npm install -g @grnsft/if-models@0.1.5`
```
╰─ npm dist-tag ls @grnsft/if-models
latest: 0.1.6-beta
```

refer to this [issue](https://github.com/Green-Software-Foundation/if/issues/474)

**Comment by narekhovhannisyan** [comment]
Hey @N33MO! Thanks for reporting an issue. Rewritten version is coming at the end of this week!

**Comment by narekhovhannisyan** [comment]
fixed with the new release
