### ISSUE TITLE
E-MEM Coefficient unit correction

### ISSUE THREAD

**Issue by Akrammasrour** [Green-Software-Foundation/if-plugins#47]
Hello GSF Team,

As demonstrated today in the Weekly meeting,  The E-MEM Plugin documentation and code includes a by-default coefficient of 0.38 kWh/GB. On the other hand the CCF Methodology states it would be rather in **W/GB**. ( Which is more convenient/credible as a Watts to Bytes Ratio )

CCF methodology : 
https://www.cloudcarbonfootprint.org/docs/methodology/#memory
E-MEM Plugin Documentation :
https://github.com/Green-Software-Foundation/if-plugins/blob/main/src/lib/e-mem/README.md

Thanks in advance
Akram,

**Comment by jmcook1186** [comment]
Hi @Akrammasrour, thanks a lot for catching this!

Fixed in #48

**Comment by Akrammasrour** [comment]
Hello Joseph,

Thanks! I saw it got merged, with great pleasure to contribute.
One small question please : I heard you mentioned in the weekly meeting
that there is a session that occurs on wednesdays as a workshop to run the
if etc..
Is there a page for the agenda of this event ? ot is it accessible via a
link ?
Thank you very much!

Akram,

Le jeu. 7 mars 2024 à 15:50, Joseph Cook ***@***.***> a
écrit :

**Comment by jmcook1186** [comment]
Hi - sorry I mised this question last week - there is also a livestream happening today at 1430 UTC that will cover some IF basics - there's also some workshop materials coming online today/tomorrow that will help you onboard. There will also be "orientation" call sessions for hackathon participants starting this week - keep eyes peeled for comms by email and on if.greensoftware.foundation.
