### ISSUE TITLE
'child_process' module can not found in '@grnsf/if-plugins/build/lib/shell  When I introduce plugins into the React project

### ISSUE THREAD

**Issue by lyxHanHan** [Green-Software-Foundation/if-plugins#60]
## Implementation details

When I introduce plugins into the React project，and use {e-Net} in if-plugin,
there will be display this issue:
'child_process' module can not found in '@grnsf/if-plugins/build/lib/shell  
## Priority

May I ask if this plugin is incompatible with the React framework?

**Comment by manushak** [comment]
Hi @lyxHanHan. I've investigated the issue. If you're explicitly using webpack, you'll need to add the following configuration to your webpack.config.js file:
`// webpack.config.js
...,
resolve: {
    extensions: [".ts", ".js"],
    fallback: {
      "child_process": false,
      // and also other packages that are not found
    }
  },`
  
However, if you're relying on the `node_module` implicitly, you'll need to add the following to your package.json file:
`"browser":{
"child_process": false
}`

Please let us know if this solution resolves your problem.

**Comment by lyxHanHan** [comment]
Solved, thank you for your help！🙏

**Comment by jmcook1186** [comment]
Closing as resolved
