### ISSUE TITLE
E_NET Plugin coefficient ratio inquiry 

### ISSUE THREAD

**Issue by Akrammasrour** [Green-Software-Foundation/if-plugins#63]
Hello,

I would like to ask about the Network coefficient that we are using in the E-NET plugin as **0.001GB** ( GigaBYTES) and the one mentioned in the CCF methodology : https://www.cloudcarbonfootprint.org/docs/methodology/#networking as 0.001 **kWh/Gb** (GigaBITS). which intrigued me.
Are they supposed to be the same ? or they come from two different methodologies ?

Thank you in advance 
Best Regards 
MASROUR Mohamed-Akram

**Comment by jmcook1186** [comment]
Hi - yes appreciate the confusion here - we had to dig in a bit to double-check when we read your issue.

The value *should* be in gigabytes per kilowatt hour, as it is currently in our impleemntation. Agree the CCF docs are a bit ambiguous when you read the networking paragraph that you linked, but if you scroll down to appendix IV and click through to the cited sources you'll see it clearly defined as "kilowatt-hours per gigabyte [kWh/GB]", e.g. here https://onlinelibrary.wiley.com/doi/full/10.1111/jiec.12630

**Comment by jmcook1186** [comment]
Closing as complete
