### ISSUE TITLE
Readme shows incorrect outputs(?)

### ISSUE THREAD

**Issue by heaversm** [Green-Software-Foundation/if-plugins#65]
I believe the readme documentation lists the improper output of the [cloud metadata plugin](https://github.com/Green-Software-Foundation/if-plugins/blob/main/src/lib/cloud-metadata/README.md)

## Rationale

Shows:

> An array containing:

    cloud/instance-type: echo input instance-type
    cloud/vendor: echo input vendor
    physical-processor: physical processor used in the given instance
    vcpus-allocated: number of vCPUs allocated to this instance
    vcpus-total: total number of vCPUs available to this instance

Should show:

> An array containing:

    cpu/thermal-design-power: [your chosen description]
    memory-available: [your chosen description]
    physical-processor: physical processor used in the given instance
    vcpus-allocated: number of vCPUs allocated to this instance
    vcpus-total: total number of vCPUs available to this instance

based on what I see in [this file](https://github.com/Green-Software-Foundation/if-plugins/blob/main/src/lib/cloud-metadata/index.ts#L106)

```
'vcpus-allocated': parseInt(instance['cpu-cores-utilized']),
'vcpus-total': parseInt(instance['cpu-cores-available']),
'memory-available': parseInt(instance['memory-available']),
'physical-processor': instance['cpu-model-name'],
'cpu/thermal-design-power': parseFloat(instance['cpu-tdp']),
```

**Comment by jmcook1186** [comment]
Yes, with the following inputs:
```
- timestamp: 2023-07-06T00:01
   duration: 10
  cloud/vendor: aws
  cloud/instance-type: m5n.large
```
the plugin yields the following outputs:

```
            "timestamp": "2023-07-06T00:01",
            "duration": 10,
            "cpu/utilization": 80,
            "cpu/thermal-design-power": 210,
            "cloud/vendor": "aws",
            "cloud/instance-type": "m5n.large",
            "cpu/energy": 0.00025568089430894314,
            "vcpus-allocated": 2,
            "vcpus-total": 96,
            "memory-available": 8,
            "physical-processor": "Intel® Xeon® Platinum 8259CL"
```

I'll update the docs page.

**Comment by jmcook1186** [comment]
Closing as complete
