### ISSUE TITLE
Simple HTML Exporter plugin not working

### ISSUE THREAD

**Issue by elieppr** [Green-Software-Foundation/if-plugins#66]
I followed the instructions on the page https://if.greensoftware.foundation/developers/how-to-visualize-results, using the example manifest listed, and I got this error:

[2024-04-02 09:52:15.043 PM] error:     plugin is not a function
TypeError:      plugin is not a function

What should I do to fix this?

**Comment by jmcook1186** [comment]
Hi @elieppr - sorry about this, but the html exporter did not get migrated over to the new IF when we refactored it a few weeks ago, and I didn't realize we hadn't removed it from the docs. It's not functional at the moment and we probably won't work on restoring it for a few weeks as we are at capacity with QA related changes. I removed the html section from the docs for now.

**Comment by jmcook1186** [comment]
Closing as complete
