### ISSUE TITLE
Make yaml the default output if an output file is specified in the CLI

### ISSUE THREAD

**Issue by heaversm** [Green-Software-Foundation/if-plugins#80]
Right now, unless you specify

```yml
outputs:
    - yaml
```

in your manifest file, when you run the CLI, e.g.

`ie --manifest manifest-input/tests/mock-observations.yml --output manifest-output/tests/mock-observations-out`

You will get the output in the terminal, not a file.

For example in the documentation [here](https://github.com/Green-Software-Foundation/if-plugins/blob/main/src/lib/mock-observations/README.md), does not work to actually generate a file. I would either update that documentation to leave out the output file, or add in the output format in sample manifest.

**Comment by jmcook1186** [comment]
Thanks - agree this isn't ideal. We are going to update the way the outputs work soon to something much more user friendly, so for now we'll just update the documentation.

**Comment by jmcook1186** [comment]
Docs updated via PR https://github.com/Green-Software-Foundation/if-plugins/pull/82
