### ISSUE TITLE
Move grafana export plugin to self hosted repository and register in the Plugin Registery

### ISSUE THREAD

**Issue by perkss** [Green-Software-Foundation/if-plugins#95]
## Rationale

With the deprecation of if-plugins we are required to move the `grafana-exporter`. 

## Implementation details

* Move the grafana-exporter plugin to own repository. @perkss 
* Register the plugin with the new plugin registry 
* Remove the code from if-plugins

## Priority

2

## Scope

N/A

## Size

6

## What does "done" look like?

Plugin removed from this repository, hosted by @perkss and registered in plugin registry

## Does this require updates to documentation or other materials??

Only applicable in this code

## Acceptance criteria

Plugin code copied into new repository and then this code can be removed
https://github.com/Green-Software-Foundation/if-plugin-website?tab=readme-ov-file#plugin-governance

**Comment by perkss** [comment]
@jmcook1186 can you assign this to me please?

**Comment by jmcook1186** [comment]
sure - thanks @perkss 
also added it to the IF project board just so we can keep track

**Comment by jmcook1186** [comment]
You can just add a deprecation notice to the if-plugins version for now instead of actually removing anything from if-plugins. That way we don't break anything before we've had time to warn our users and give some grace period. @perkss

**Comment by perkss** [comment]
New plugin repo: https://github.com/perkss/grafana-export

**Comment by perkss** [comment]
@jmcook1186 do you have an example of the deprecation notice to put? Or the style I should use? Just in the docstring like this: https://jsdoc.app/tags-deprecated?
